#ifndef COLOR_H
#define COLOR_H


#define COLOR_BLACK 0
#define COLOR_RED 1
#define COLOR_GREEN 2
#define COLOR_YELLOW 3
#define COLOR_BLUE 4
#define COLOR_MAGENTA 5
#define COLOR_CYAN 6
#define COLOR_WHITE 7

#define COLOR_FOREGROUND 30
#define COLOR_FOREGROUND_BLACK 30
#define COLOR_FOREGROUND_RED 31
#define COLOR_FOREGROUND_GREEN 32
#define COLOR_FOREGROUND_YELLOW 33
#define COLOR_FOREGROUND_BLUE 34
#define COLOR_FOREGROUND_MAGENTA 35
#define COLOR_FOREGROUND_CYAN 36
#define COLOR_FOREGROUND_WHITE 37

#define COLOR_FOREGROUND_BRIGHT 90
#define COLOR_FOREGROUND_BRIGHT_BLACK 90
#define COLOR_FOREGROUND_BRIGHT_RED 91
#define COLOR_FOREGROUND_BRIGHT_GREEN 92
#define COLOR_FOREGROUND_BRIGHT_YELLOW 93
#define COLOR_FOREGROUND_BRIGHT_BLUE 94
#define COLOR_FOREGROUND_BRIGHT_MAGENTA 95
#define COLOR_FOREGROUND_BRIGHT_CYAN 96
#define COLOR_FOREGROUND_BRIGHT_WHITE 97

#define COLOR_BACKGROUND 40
#define COLOR_BACKGROUND_BLACK 40
#define COLOR_BACKGROUND_RED 41
#define COLOR_BACKGROUND_GREEN 42
#define COLOR_BACKGROUND_YELLOW 43
#define COLOR_BACKGROUND_BLUE 44
#define COLOR_BACKGROUND_MAGENTA 45
#define COLOR_BACKGROUND_CYAN 46
#define COLOR_BACKGROUND_WHITE 47

#define COLOR_BACKGROUND_BRIGHT 100
#define COLOR_BACKGROUND_BRIGHT_BLACK 100
#define COLOR_BACKGROUND_BRIGHT_RED 101
#define COLOR_BACKGROUND_BRIGHT_GREEN 102
#define COLOR_BACKGROUND_BRIGHT_YELLOW 103
#define COLOR_BACKGROUND_BRIGHT_BLUE 104
#define COLOR_BACKGROUND_BRIGHT_MAGENTA 105
#define COLOR_BACKGROUND_BRIGHT_CYAN 106
#define COLOR_BACKGROUND_BRIGHT_WHITE 107

#define SGR_SEQ_START "\033["
#define SGR_SEQ_END "m"
#define SGR_FORMAT_SEQ_START "\033[%sm"

#define RESET_SEQ "\033[0m"
#define __COLOR_CODE(col) # col
#define COLOR_CODE(col) __COLOR_CODE(col)
#define COLOR_SEQ(col) "\033[" COLOR_CODE(col) "m"
#define BOLD_SEQ "\033[1m"
#define UNDERLINE_SEQ "\033[4m"


#endif /* COLOR_H */
