#ifndef COLOR_H
#define COLOR_H


#define COLOR_BLACK 0
#define COLOR_RED 1
#define COLOR_GREEN 2
#define COLOR_YELLOW 3
#define COLOR_BLUE 4
#define COLOR_MAGENTA 5
#define COLOR_CYAN 6
#define COLOR_WHITE 7

#define COLOR_FOREGROUND 30
#define COLOR_FOREGROUND_BLACK 30
#define COLOR_FOREGROUND_RED 31
#define COLOR_FOREGROUND_GREEN 32
#define COLOR_FOREGROUND_YELLOW 33
#define COLOR_FOREGROUND_BLUE 34
#define COLOR_FOREGROUND_MAGENTA 35
#define COLOR_FOREGROUND_CYAN 36
#define COLOR_FOREGROUND_WHITE 37

#define COLOR_BACKGROUND 40
#define COLOR_BACKGROUND_BLACK 40
#define COLOR_BACKGROUND_RED 41
#define COLOR_BACKGROUND_GREEN 42
#define COLOR_BACKGROUND_YELLOW 43
#define COLOR_BACKGROUND_BLUE 44
#define COLOR_BACKGROUND_MAGENTA 45
#define COLOR_BACKGROUND_CYAN 46
#define COLOR_BACKGROUND_WHITE 47

// const char RESET_SEQ[] = "\033[0m";
// const char COLOR_SEQ[] = "\033[1;{}m";
// const char BOLD_SEQ[] = "\033[1m";
#define RESET_SEQ "\033[0m"
#define COLOR_SEQ_FORMAT "\033[1;%dm"
#define COLOR_CODE(col) # col
#define COLOR_SEQ(col) "\033[1;" COLOR_CODE(col) "m"
#define BOLD_SEQ "\033[1m"


#endif /* COLOR_H */
